sudo: false
language: node_js
node_js:
    - stable
cache:
    directories:
        - node_modules
notifications:
    email: false
branches:
    only:
        - master
script:
  - npm run lint
  - npm test